plugins {
  id 'java'
}

group = 'boot.innoslate.test'
version = '4.x.x'

tasks.withType(JavaCompile).configureEach {
  sourceCompatibility = JavaVersion.VERSION_21
  targetCompatibility = JavaVersion.VERSION_21
  options.encoding = 'UTF-8'
  options.deprecation = true
}

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
  // Innoslate SDK Jar File
  testImplementation files('libs/innoslate4x-java-sdk.jar')
  testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  testImplementation 'org.apache.poi:poi-ooxml:5.5.1'
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
  // Assign default values to Innoslate SDK System Properties and add them to the test system properties
  String username = providers.gradleProperty("username").getOrNull()
  String password = providers.gradleProperty("password").getOrNull()
  String innoslateSDKDomain = providers.gradleProperty("innoslateSDKDomain").getOrElse("")
  String innoslateUserApiKey = providers.gradleProperty("innoslateUserApiKey").getOrNull()
  String innoslateUserApiSalt = providers.gradleProperty("innoslateUserApiSalt").getOrNull()
  String innoslateCloudApiKey = providers.gradleProperty("innoslateCloudApiKey").getOrNull()
  String innoslateCloudApiSalt = providers.gradleProperty("innoslateCloudApiSalt").getOrNull()
  String innoslateOrganizationSlug = providers.gradleProperty("innoslateOrganizationSlug").getOrElse("")
  int innoslateProjectId = providers.gradleProperty("innoslateProjectId").getOrElse("0").toInteger()

  if (username != null) systemProperty("username", username)
  if (password != null) systemProperty("password", password)
  systemProperty("innoslateSDKDomain", innoslateSDKDomain)
  if (innoslateUserApiKey != null) systemProperty("innoslateUserApiKey", innoslateUserApiKey)
  if (innoslateUserApiSalt != null) systemProperty("innoslateUserApiSalt", innoslateUserApiSalt)
  if (innoslateCloudApiKey != null) systemProperty("innoslateCloudApiKey", innoslateCloudApiKey)
  if (innoslateCloudApiSalt != null) systemProperty("innoslateCloudApiSalt", innoslateCloudApiSalt)
  systemProperty("innoslateOrganizationSlug", innoslateOrganizationSlug)
  systemProperty("innoslateProjectId", innoslateProjectId)
}

jar {
  enabled = false
}
